### ISSUE TITLE
check that analysis deals with neutral mutations appropriately

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/analysis2#29] opened 2021-12-11 15:56 UTC
@xin-huang points out in https://github.com/popsim-consortium/stdpopsim/issues/1141 that removing neutral mutations affects the results of this pipeline, which should not happen. Maybe something about how selected mutations are identified needs to be adjusted?

**Comment by xin-huang** [comment] 2021-12-11 16:23
Can I let `stdpopsim` to simulate both neutral and selected mutations simultaneously with `SLiM`?
I think the default behavior is simulating selected mutations with `SLiM` first and overlapping neutral mutations later with `msprime`?

**Comment by petrelharp** [comment] 2021-12-11 16:41
>  I think the default behavior is simulating selected mutations with SLiM first and overlapping neutral mutations later with msprime?

Yes, that's right. Why do you want to do the neutral mutations with SLiM?

**Comment by xin-huang** [comment] 2021-12-11 17:04
Here are two slim scripts generated by the old and new DFE API.
The only difference is 

`initializeGenomicElementType(0, c(0, 1), c(0.0, 0.7));    |     initializeGenomicElementType(0, c(0, 1), c(0.3, 0.7));`

To verify the results, I will simulate both neutral and selected mutations simultaneously with `SLiM` using `proportions=(0.3, 0.7)`,
and also use the overlapping technique to first simulate selected mutations only in `SLiM` with `proportions=(0.3, 0.7)` and `proportions=(0.0, 0.7)`, then simulate neutral mutations with `msprime`

[stdpopsim_Gutenkunst09_HuberDFE.old.slim.txt](https://github.com/popsim-consortium/analysis2/files/7697423/stdpopsim_Gutenkunst09_HuberDFE.old.slim.txt)
[stdpopsim_Gutenkunst09_HuberDFE.new.slim.txt](https://github.com/popsim-consortium/analysis2/files/7697424/stdpopsim_Gutenkunst09_HuberDFE.new.slim.txt)

**Comment by petrelharp** [comment] 2021-12-11 17:31
Hm, let's see. One note is that because SLiM normalizes proportions, if that's the only difference between the scripts, then
```
initializeGenomicElementType(0, c(0, 1), c(0.3, 0.7));
```
has only 70% as many selected mutations as
```
initializeGenomicElementType(0, c(0, 1), c(0.0, 0.7));
```
So to make the two scripts equivalent otherwise you need to set the mutation rate to be smaller (multiplied by 0.7) in the second script.

But, let's see; is the only reason you want to do this for verification? Like, to check that we're adding neutral mutations correctly?

**Comment by xin-huang** [comment] 2021-12-11 22:33
It is straightforward to simulate neutral and selected mutations together in `SLiM` for verifying the pipeline, because we don't need to figure out how to rescale mutation rates to make the scripts comparable.

Users still can specify any neutral proportions as they like in the catalog. But when `stdpopsim` generates intermediate `SLiM` scripts, it will automatically set neutral proportions to 0. Just like mutation rates, e.g. in `OutOfAfrica_3G09` model, the mutation rate is `2.35e-8`, but the slim scripts above automatically set the mutation rate to `1.645e-8` (2.35e-8*0.7) if nonneutral proportions is 0.7.

**Comment by xin-huang** [comment] 2021-12-11 22:41
Or maybe the mutation rate should remain `2.35e-8` when generated by the new DFE API, and `SLiM` will figure out the correct mutation rate is `2.35e-8*0.7` automatically?

**Comment by petrelharp** [comment] 2021-12-12 15:29
> Or maybe the mutation rate should remain 2.35e-8 when generated by the new DFE API, and SLiM will figure out the correct mutation rate is 2.35e-8*0.7 automatically?

Right: it should be invisible to the user - this is what happens in the code, [here](https://github.com/popsim-consortium/stdpopsim/blob/main/stdpopsim/slim_engine.py#L634).

**Comment by xin-huang** [comment] 2021-12-14 01:18
Hi @petrelharp 
Here are the [results](https://github.com/xin-huang/validation/blob/main/slim_only/chr21/plots/chr21/dfe.inference.benchmark.pdf) from SLiM simulation with both neutral and selected mutations together.
It is similar to the [results](https://github.com/xin-huang/analysis2/blob/dev/benchmark/plots/chr21/dfe.inference.benchmark.old.DFE.API.pdf) from the old DFE API. Therefore, I don't think my pipeline causes the difference between the old and new DFE API.
The SLiM script to simulate the above data is [here](https://github.com/xin-huang/validation/blob/main/slim_only/stdpopsim_Gutenkunst09_HuberDFE.slim)
You can also find other files in https://github.com/xin-huang/validation/tree/main/slim_only

**Comment by petrelharp** [comment] 2021-12-14 17:48
Here's the bit of the anaysis code: https://github.com/popsim-consortium/analysis2/blob/6f5ff400223153ba5621dbcf6ddab15174f0b473/benchmark/Snakefile#L110

**Comment by petrelharp** [comment] 2021-12-14 17:51
We are currently identifying selected mutations using mutation types, which is not stable. We need to look at the selection coefficient instead.

**Comment by andrewkern** [comment] 2021-12-15 19:21
something that occurred to me in conversation with @mufernando today-- using mutation types directly from the tree sequence _isn't_ something that would ever be available to the empiricist. 

i wonder if @xin-huang you should just be calculating the frequency spectra from VCF output (or similar) from the tree sequence, rather than what you are trying to do here?

**Comment by xin-huang** [comment] 2021-12-15 19:39
> something that occurred to me in conversation with @mufernando today-- using mutation types directly from the tree sequence _isn't_ something that would ever be available to the empiricist.
> 
> i wonder if @xin-huang you should just be calculating the frequency spectra from VCF output (or similar) from the tree sequence, rather than what you are trying to do here?

Hi @andrewkern I tried to use VCF output before. But `tskit.TreeSequence.write_vcf` doesn't output the metadata from SLiM. Therefore, I can't separate neutral and non-neutral mutations in VCF output

**Comment by andrewkern** [comment] 2021-12-15 19:47
sure but you could separate them based on the annotation, no? in real data that is what you would use right?

**Comment by xin-huang** [comment] 2021-12-15 19:53
In real data, I use `annovar` to annotate mutations to synonymous and non-synonymous mutations. Then I use synonymous mutations as neutral mutations, and non-synonymous mutations as non-neutral mutations.

**Comment by andrewkern** [comment] 2021-12-15 20:03
seems like that should work here, but just separated into our annotation regions (to take the place of non-syn) or not (synonymous)

**Comment by mufernando** [comment] 2021-12-15 22:00
The problem is you cannot separate the neutral from the non-neutral
mutations within exons (the way we are simulating it right now). Within
exons 70% of mutations are deleterious and 30% are neutral. If we had a
more complicated model with codons then we would separate nonsyn vs syn.

**Comment by andrewkern** [comment] 2022-02-16 17:54
that's correct. closing.

**Closed by andrewkern** 2022-02-16 17:54 UTC
