### ISSUE TITLE
also run pipeline on constant-size population also

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/analysis2#33] opened 2022-01-25 17:20 UTC
... as discussed in the meeting, for comparison.

**Comment by xin-huang** [comment] 2022-01-25 17:47
I can do this

**Comment by izabelcavassim** [comment] 2022-02-16 17:41
let's add that to the config simulation file and close this issue @xin-huang

**Comment by andrewkern** [comment] 2022-02-16 17:56
it's already in the default config here https://github.com/popsim-consortium/analysis2/blob/c9cac53b619a5bbab54a9bde6c10a0d2755413b8/workflows/config/snakemake/config.yaml#L8

**Comment by andrewkern** [comment] 2022-02-16 17:56
going to keep this issue open though as I'd like to see some QC runs of constant popn size through the new pipeline

**Comment by xin-huang** [comment] 2022-02-17 17:57
Here are the plots using simulated data from the constant model with the new workflow https://github.com/popsim-consortium/analysis2/pull/43

![Constant dfe inference benchmark](https://user-images.githubusercontent.com/12013600/154539952-56b2bdf8-dc05-4d28-9e79-22c4dbf13932.png)

I think I missed a factor of 2 in previous calculation for |E(s)|, because SLiM defines genotype fitnesses as 1, 1+sh, 1+s, while `dadi` and `polyDFE` defines genotype fitnesses as 1, 1+2sh, 1+2s. Therefore `s_SLiM = 2*s_dadi = 2*s_polyDFE`

For `dadi`, `E(s_dadi) = shape*scale/(theta_ns/2*mu*L_ns)` because `E(s_dadi) = shape*scale/(2*Na)` and `Na = theta_ns/(4*mu*L_ns)`. See https://dadi.readthedocs.io/en/latest/user-guide/dfe-inference/
For `polyDFE`, `E(s_polyDFE) = mu*S_d/theta_bar` because `S_d = 4*Ne*E(s_polyDFE)` and `theta_bar = 4*Ne*mu`. See https://academic.oup.com/genetics/article/207/3/1103/5930676 Figure 1

@RyanGutenkunst

**Comment by RyanGutenkunst** [comment] 2022-02-17 19:24
@xin-huang What is going on with DFE-alpha? Is it just inferring zero selection?

**Comment by xin-huang** [comment] 2022-02-17 19:40
@RyanGutenkunst I think it is because `DFE-alpha` does not perform well with unfolded spectra. @chriscrsmith

**Comment by chriscrsmith** [comment] 2022-02-17 23:12
I spent a little time trying to fine tune the settings for DFEalpha using unfolded FS and it always performed poorly. Folded looked a lot better although still not perfect.

**Comment by 15787833237** [comment] 2022-03-15 08:58
> @RyanGutenkunst I think it is because `DFE-alpha` does not perform well with unfolded spectra. @chriscrsmith 

确实  我在用展开的SFS跑出来的结果总是不合理  我试试折叠的  再不行我试试大神你的软件！

**Comment by xin-huang** [comment] 2022-03-15 12:39
> > @RyanGutenkunst I think it is because `DFE-alpha` does not perform well with unfolded spectra. @chriscrsmith
> 
> 确实 我在用展开的SFS跑出来的结果总是不合理 我试试折叠的 再不行我试试大神你的软件！

@15787833237 also confirmed DFE-alpha results with unfolded SFS are not reasonable in their studies

**Comment by 15787833237** [comment] 2022-03-15 13:03
> > > @RyanGutenkunst I think it is because `DFE-alpha` does not perform well with unfolded spectra. @chriscrsmith
> > 
> > 
> > 确实 我在用展开的SFS跑出来的结果总是不合理 我试试折叠的 再不行我试试大神你的软件！
> 
> @15787833237 also confirmed DFE-alpha results with unfolded SFS are not reasonable in their studies

But  there is any reference when setting up the DFE model? Moreover, I think it is metaphysics....

**Comment by xin-huang** [comment] 2022-03-15 13:39
> > > > @RyanGutenkunst I think it is because `DFE-alpha` does not perform well with unfolded spectra. @chriscrsmith
> > > 
> > > 
> > > 确实 我在用展开的SFS跑出来的结果总是不合理 我试试折叠的 再不行我试试大神你的软件！
> > 
> > 
> > @15787833237 also confirmed DFE-alpha results with unfolded SFS are not reasonable in their studies
> 
> But there is any reference when setting up the DFE model? Moreover, I think it is metaphysics....

This paper https://doi.org/10.1534/genetics.112.148023 found different DFE models may fit different species. However, `DFE-alpha` and `polyDFE` both assume and infer a gamma DFE model, while `dadi` can infer several DFE models (https://dadi.readthedocs.io/en/latest/api/dadi/DFE/PDFs.html).

**Comment by RyanGutenkunst** [comment] 2022-07-08 21:59
@xin-huang Regarding factors of 2...
SLiM defines s as the selective effect on the homozygote [Section 1.3 of SLiM manual].
dadi defines s as the selective effect on the heterozygote [[https://dadi.readthedocs.io/en/latest/api/dadi/PhiManip.html#dadi.PhiManip.phi_1D](https://dadi.readthedocs.io/en/latest/api/dadi/PhiManip.html#dadi.PhiManip.phi_1D)]
polyDFE is like dadi, with s as the effect on the heterozygote [[https://academic.oup.com/genetics/article/207/3/1103/5930676](https://academic.oup.com/genetics/article/207/3/1103/5930676)]
DFE-alpha is like SLiM, with s as the effect on the homozygote [[https://academic.oup.com/genetics/article/177/4/2251/6064397](https://academic.oup.com/genetics/article/177/4/2251/6064397)]
GRAPES is like polyDFE and dadi, with s as the effect on the heterozygote [[https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1005774](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1005774)]

So there's a factor of two between the groups
(SLiM, DFE-alpha) versus (dadi, polyDFE, GRAPES).

Heh... Pop gen is such a mess sometimes...

**Closed** 2024-06-04 21:25 UTC
